name: clock_alarm
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  drift: ^1.0.1
  sqlite3_flutter_libs: ^0.5.1
  path_provider: ^2.0.7
  path: ^1.8.0
  flutter_bloc: ^8.0.0
  get_it: ^7.2.0
  dartz: ^0.10.0
  equatable: ^2.0.3
  device_preview: ^1.0.0-alpha.15
  flutter_slidable: ^1.1.0
  flutter_local_notifications: ^9.1.4
  timezone: ^0.8.0
  fl_chart: ^0.40.2
  nav_router:
    git:
      url: https://github.com/dwikyhardi/nav_router
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^1.0.2
  build_runner: ^2.1.5
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
